[versions]
agp = "9.2.1"
kermit = "2.1.0"
kotlin = "2.4.10"
compose-multiplatform = "1.10.3"
activity-compose = "1.13.0"
material3 = "1.9.0"
coroutines = "1.11.0"

publishing = "0.37.0"

[libraries]

activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
composeRuntime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }
composeFoundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }
composeUi = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-multiplatform" }
composeResources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-multiplatform" }
composeRuntimeSaveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "compose-multiplatform" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
composeMaterial3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
publishing = { id = "com.vanniktech.maven.publish", version.ref = "publishing" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }