[versions]
agp = "8.13.1"
kotlin = "2.2.21"
compose-multiplatform = "1.9.3"
publishing = "0.35.0"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
publishing = { id = "com.vanniktech.maven.publish", version.ref = "publishing" }